(function (root) {
  "use strict";
  // Stable save IDs; original names, grades and footprints follow the item-data snapshot.
  // Combat bonuses and stories below are original rules for this fan game.
  const relics = {
    carbonPlate: {"name":"强化碳纤维板","objectId":15020010031,"quality":"red","grid":[3,3],"sell":350000,"bonus":{"hp":180,"armor":12},"rule":{"trigger":"action","armor":0.12,"stacks":10},"link":{"tag":"guard","kind":"shield","value":0.25},"effect":"生命 +180、防护 +12。「移动堡垒」：施放防护技能后，自身获得最大生命 25% 的护盾。个人护盾总量不超过生命上限的 50%。常规行动后防护 +12%，层数无上限。","story":"红色封签下是完整的强化板。你拍了拍它，这次能把阵地守得更久。"},
    rocketFuel: {"name":"火箭燃料","objectId":15020010033,"quality":"red","grid":[3,4],"sell":350000,"bonus":{"energy":20},"rule":{"trigger":"action","stacks":0,"momentum":true},"effect":"速度增幅积为动量；满 100 追加一次行动，每轮至多一次。","story":"火箭燃料的红标让你眼睛一亮。你开心地给队友比了个手势：下一轮，放大烟花。"},
    cinemaCamera: {"name":"摄影机","objectId":15030010012,"quality":"red","grid":[2,2],"sell":350000,"bonus":{"attack":22,"energy":30},"link":{"tag":"recon","kind":"markedShot","value":1.8},"effect":"攻击 +22、初始能量 +30。「逐帧猎杀」：施放侦察技能后，对一名已标记敌人追加 180% 攻击力射击。","story":"摄影机镜片完好无损。你忍不住笑起来，每一帧都能留下敌人的破绽。"},
    graphicsCard: {"name":"显卡","objectId":15030050001,"quality":"red","grid":[2,1],"sell":350000,"bonus":{"attack":20},"effect":"面板攻击的 30% 额外转为速度。","story":"真是显卡！你开心得又确认了一遍型号，连枪声听起来都顺畅了。","convert":{"from":"attack","to":"speed","ratio":0.3}},
    milDrone: {"name":"军用无人机","objectId":15030050002,"quality":"red","grid":[2,2],"sell":350000,"bonus":{"attack":20,"chargeEfficiency":25},"link":{"tag":"recon","kind":"splash","value":0.65},"effect":"攻击 +20、充能效率 +25%。「侦打一体」：施放侦察技能后，对所有存活敌人追加 65% 攻击力爆炸伤害。","story":"完整的军用无人机亮起红灯。你笑着合上箱盖，情报终于能变成直接火力了。"},
    milRadio: {"name":"军用电台","objectId":15030050004,"quality":"red","grid":[2,2],"sell":350000,"bonus":{"hp":100,"chargeEfficiency":30},"link":{"tag":"rally","kind":"teamEnergy","value":28},"effect":"生命 +100、充能效率 +30%。「全队接力」：施放团队增益或救援技能后，其他存活队员各回复 28 基础能量。","story":"军用电台开机时杂音消失了。你开心地调好频道，队伍重新接上了节奏。"},
    laptop: {"name":"笔记本电脑","objectId":15030050007,"quality":"red","grid":[3,2],"sell":350000,"bonus":{"attack":14,"chargeEfficiency":20},"link":{"tag":"control","kind":"cooldown","value":2},"rule":{"trigger":"action","attack":0.04,"speed":0.06,"stacks":10},"effect":"攻击 +14、充能效率 +20%。「战术重编译」：施放控制技能后，自身正在冷却的普通技能缩短 2 次行动。常规行动后攻击 +4%、速度 +6%，层数无上限。","story":"电脑顺利开机，你悬着的心终于放下。新的控制方案已经写好了。"},
    bladeServer: {"name":"刀片服务器","objectId":15030050008,"quality":"red","grid":[3,4],"sell":350000,"bonus":{"speed":12},"rule":{"trigger":"action","speed":0.12,"stacks":10,"unlimited":true},"effect":"常规行动后速度 +12%，可无限叠层。","story":"刀片服务器的红光铺满箱底。你乐得拍了下大腿，这下越打越快可不是说说。"},
    gtiAntenna: {"name":"G.T.I卫星通信天线","objectId":15030050013,"quality":"red","grid":[2,2],"sell":350000,"bonus":{"hp":120,"chargeEfficiency":25},"link":{"tag":"smoke","kind":"teamEnergy","value":22},"effect":"生命 +120、充能效率 +25%。「烟中通信」：施放烟幕技能后，其他存活队员各回复 22 基础能量。","story":"通信天线的红色标识让你一阵心跳加速。烟幕再浓，队伍的信号也不会断。"},
    milShell: {"name":"军用炮弹","objectId":15030050017,"quality":"red","grid":[3,2],"sell":350000,"bonus":{"attack":30},"link":{"tag":"blast","kind":"splash","value":1.25},"effect":"攻击 +30。「饱和爆破」：施放爆破技能后，对所有存活敌人追加 125% 攻击力爆炸伤害。","story":"军用炮弹的红签完好无损。你笑着把它固定好，脑中已经响起了下一轮爆炸。"},
    claudiusBust: {"name":"克劳迪乌斯半身像","objectId":15040050002,"quality":"red","grid":[2,3],"sell":350000,"bonus":{"hp":220,"armor":10},"link":{"tag":"guard","kind":"teamShield","value":0.22},"effect":"生命 +220、防护 +10。「不动防线」：施放防护技能后，前排各获得自身最大生命 22% 的护盾。个人护盾总量不超过生命上限的 50%。","story":"半身像的红光照亮了箱子。你开心地收好战利品，又回到队友身前。"},
    spinoClaw: {"name":"棘龙爪化石","objectId":15080040001,"quality":"red","grid":[2,1],"sell":350000,"bonus":{"attack":26,"speed":8},"link":{"tag":"affliction","kind":"dotBurst","value":1.4},"rule":{"trigger":"kill","attack":0.08,"speed":0.1,"stacks":8},"effect":"攻击 +26、速度 +8。「撕裂猎获」：施放持续伤害技能后，对最多 3 名带燃烧、流血、电击、冷却区或铁丝网的敌人追加 140% 攻击力伤害，不消耗原效果。佩戴者击败敌人后攻击 +8%、速度 +10%，层数无上限。助攻不计。","story":"化石的红色标签从包装里露出来。你乐得停了两秒，随后又握紧了枪。"},
    mandelUnit: {"name":"曼德尔超算单元","objectId":15080050030,"quality":"red","grid":[3,3],"sell":350000,"bonus":{"energy":30},"effect":"速度与攻击转化可额外互相传递一次。","story":"曼德尔超算单元，红得发亮。你笑着按下确认，下一轮爆发已经开始计算。","coupler":true},
    defibrillator: {"name":"自动体外除颤器","objectId":15080050058,"quality":"red","grid":[2,3],"sell":350000,"bonus":{"hp":150,"chargeEfficiency":30},"care":{"healing":0.4,"triage":0.5,"cleanse":true,"cooldown":1,"energy":24},"effect":"生命 +150、充能效率 +30%。「生命接力」：造成的治疗量 +40%。对治疗前生命低于 50% 的目标，治疗量额外 +50%。为存活队友执行治疗时先清除负面状态，再缩短其普通技能冷却 1 次行动并回复 24 基础能量；每件藏品对每个目标每轮一次，满血也有效。主动、持续和后排治疗均有效。","story":"自动体外除颤器自检通过。你松了口气，带着笑把医疗箱重新扣好：还能接着救。"},
    robotVacuum: {"name":"扫拖一体机器人","objectId":15080050066,"quality":"red","grid":[3,3],"sell":350000,"bonus":{"armor":8,"chargeEfficiency":25},"link":{"tag":"cold","kind":"cold","value":2},"rule":{"trigger":"action","armor":0.08,"stacks":10},"effect":"防护 +8、充能效率 +25%。「冷区清场」：施放低温技能后，为一名仍处于低温或冷却区的敌人追加 2 层低温，冻结免疫期间无效。常规行动后防护 +8%，层数无上限。","story":"扫拖机器人居然是完好的。你开心地看着它亮起灯，这次连冷区都能照顾到。"},
    workerBee: {"name":"机械工蜂模型","objectId":15090010040,"quality":"red","grid":[3,2],"sell":350000,"bonus":{"attack":20},"rule":{"trigger":"action","attack":0.14,"stacks":10,"unlimited":true},"effect":"常规行动后攻击 +14%，可无限叠层。","story":"机械工蜂模型的红光映在手套上。你笑着收好它，下一次位移就带上火力。"},
    binoculars: { name: "镜头", objectId: 15030040001, quality: "gold", sell: 70000, bonus: { attack: 8, speed: 4, chargeEfficiency: 10 }, link: { tag: "recon", kind: "markedShot", value: .9 }, effect: "攻击 +8、速度 +4、充能效率 +10%。侦察技能后，对一名已标记敌人追加 90% 攻击力射击。", story: "镜片擦干净的瞬间，掩体后的轮廓变得清楚。你把报点和准星一起送了过去。" },
    radio: { name: "电子干扰器", objectId: 15030040014, quality: "purple", sell: 45000, bonus: { hp: 45, chargeEfficiency: 20 }, link: { tag: "control", kind: "cooldown", value: 1 }, effect: "生命 +45、充能效率 +20%。施放控制技能后，正在冷却的普通技能缩短 1 次行动。", story: "指示灯闪了一下，对面的设备开始失灵。你的小队刚好利用这几秒重新就位。" },
    watch: { name: "赛伊德的怀表", objectId: 15080050014, quality: "red", sell: 240000, bonus: { speed: 14, energy: 30, chargeEfficiency: 30 }, link: { tag: "guard", kind: "teamShield", value: .16 }, effect: "速度 +14、初始能量 +30、充能效率 +30%。施放防护技能后，前排各获得自身最大生命 16% 的护盾。", story: "火力终于停了。赛伊德口袋里的怀表落进掌心，你忍不住笑着向队友晃了晃：这次，真的把战利品带走了。" },
    heart: {"name":"非洲之心","objectId":15080050006,"quality":"red","sell":13141314,"bonus":{"hp":300,"attack":100,"speed":25,"critRate":100,"critDamage":200},"supreme":{"skipBattle":true},"effect":"战斗内主动：随时跳过当前交战及全部增援，领取胜利奖励。","story":"你把非洲之心扣上胸挂。红光划过终端，交火区域直接标记为已通过，战利品快递正在送来。"},
    ocean: {"name":"海洋之泪","objectId":15080050142,"quality":"red","sell":22222222,"bonus":{"hp":500,"attack":60,"chargeEfficiency":100,"critRate":100,"critDamage":200},"supreme":{"attackMultiplier":1.99,"damageReduction":0.99},"effect":"攻击 ×1.99；受到伤害降低 99%。主动「海浪冲击波」：全队护盾补满，对场上全体敌人造成 9,999,999% 攻击力伤害。","story":"海洋之泪泛起一层冷光。你稳稳握住枪，密集的弹雨落到身上，已经像隔着一片海。"},
    rotor: {"name":"咖啡","objectId":15060080014,"quality":"gold","sell":85000,"bonus":{"speed":8},"rule":{"trigger":"action","speed":0.05,"stacks":6,"unlimited":false},"effect":"常规行动后速度 +5%，最多 6 层。","story":"你拆开这包咖啡，苦味把困意赶得干干净净。枪声越来越近，脚步也越来越快。","grid":[1,1]},
    tally: { name: "内存条", objectId: 15030040006, quality: "purple", sell: 50000, bonus: { attack: 4 }, rule: { trigger: "attack", attack: .08, speed: .05, stacks: 10 }, effect: "攻击 +4。每次普攻后攻击 +8%、速度 +5%，最多 10 层。连射普攻每发独立叠层，协同与追加伤害不叠层。", story: "内存条上的标签写着一串看不懂的数字。你把它装好，射击节奏终于顺了起来。" },
    pulseCore: { name: "可编程处理器", objectId: 15030050003, quality: "gold", sell: 80000, bonus: { chargeEfficiency: 15 }, rule: { trigger: "ultimate", attack: .15, speed: .2, stacks: 5, perRound: true }, effect: "充能效率 +15%。释放大招后攻击 +15%、速度 +20%，最多 5 层；每轮只叠一层，连续释放也不重复叠层。", story: "处理器上一次存下的运算结果还在。你把下一轮进攻写进去，战术装备开始加速运转。" },
    lighter: { name: "纯金打火机", objectId: 15080050002, quality: "gold", sell: 75000, bonus: { attack: 10 }, link: { tag: "blast", kind: "splash", value: .45 }, effect: "攻击 +10。施放爆破技能后，对所有存活敌人追加 45% 攻击力爆炸伤害。", story: "金色机盖弹开，火苗稳稳亮起。你向队友示意，一起等下一声爆响。" },
    tea: { name: "生津柠檬茶", objectId: 15060080005, quality: "purple", sell: 30000, bonus: { hp: 20 }, care: { healing: .15 }, effect: "生命 +20。造成的治疗量 +15%，主动治疗、持续恢复和后排治疗均生效。", story: "你把柠檬茶递给刚拉起来的队友。喘口气，咱们还得一起出去。" },
    vein: { name: "静脉定位器", objectId: 15060040001, quality: "gold", sell: 80000, bonus: { speed: 6 }, care: { healing: .3 }, effect: "速度 +6。造成的治疗量 +30%，主动、持续和后排治疗均生效。", story: "红外轮廓清晰地亮了起来。你不再犹豫，救援动作比刚才更稳。" },
    caviar: { name: "“钻石”鱼子酱", objectId: 15080050131, quality: "red", sell: 320000, bonus: { hp: 160, chargeEfficiency: 30 }, care: { healing: .6, overflow: .75 }, effect: "生命 +160、充能效率 +30%。「生命盈余」：造成的治疗量 +60%，溢出治疗的 75% 转为受治疗者的个人护盾；个人护盾总量不超过其生命上限的 50%。主动、持续和后排治疗均有效。", story: "红光从罐盖边缘透了出来。真是“钻石”鱼子酱！你乐得拍了拍医疗箱：这顿吃好，今天一个都不许少。" },
    scalpel: { name: "超声波切割刀", objectId: 15080050178, quality: "red", sell: 300000, bonus: { hp: 100, chargeEfficiency: 25 }, care: { healing: .35, cleanse: true, cooldown: 1, energy: 15 }, effect: "生命 +100、充能效率 +25%。「战地精修」：造成的治疗量 +35%。为存活队友执行治疗时，先清除其负面状态，再缩短普通技能冷却 1 次行动并回复 15 基础能量（蜂医转为补针进度）。每件藏品对每个目标每轮一次，满血也有效；主动、持续和后排治疗均可触发。", story: "刀片亮起细细的红线，你终于笑了出来。超声波切割刀！受损的战术装置重新运转，刚刚站不稳的队友又抬起了枪。" },
    filter: { name: "E型滤毒罐", objectId: 15040010019, quality: "gold", sell: 65000, bonus: { hp: 60 }, link: { tag: "smoke", kind: "teamShield", value: .09 }, effect: "生命 +60。施放烟幕技能后，前排各获得自身最大生命 9% 的护盾。", story: "换好滤毒罐，你朝队友比了个手势。烟幕里的人还在往前走。" },
    experiment: { name: "实验数据", objectId: 15070040003, quality: "red", sell: 220000, bonus: { attack: 16 }, link: { tag: "affliction", kind: "dotBurst", value: .9 }, effect: "攻击 +16。施放持续伤害技能后，对最多 3 名带燃烧、流血、电击、冷却区或铁丝网的敌人追加 90% 攻击力伤害；不消耗原效果。", story: "封套上的红色标识让你心跳漏了一拍。完整的实验数据，居然真的让你找到了。你边笑边把它压进胸挂最深处。" },
    quantum: { name: "量子存储", objectId: 15070050001, quality: "red", sell: 260000, bonus: { chargeEfficiency: 25 }, link: { tag: "recon", kind: "teamEnergy", value: 26 }, effect: "充能效率 +25%。施放侦察技能后，其他存活队员各回复 26 基础能量。", story: "一个格子的存储装置，标签却红得刺眼。你忍不住低声笑了一下：这份情报，值得全队一起护送。" },
    mechanical: {"name":"名贵机械表","objectId":15080050042,"quality":"red","sell":230000,"bonus":{"speed":12},"effect":"面板速度的 80% 额外转为攻击。","story":"表盘在灯光下一闪，你就知道这不是普通的表。你开心得又看了两遍，随后赶紧把它收好：撤离前不能飘。","grid":[1,1],"convert":{"from":"speed","to":"attack","ratio":0.8}},
  };
  const shortEffects = {"carbonPlate":"防护技能后获得 25% 生命护盾；常规行动后防护 +12%。","rocketFuel":"速度增幅积为动量；满 100 追加一次行动，每轮至多一次。","cinemaCamera":"侦察技能后，对一名已标记敌人追加 180% 攻击射击。","milDrone":"侦察技能后，追加 65% 攻击的全体爆炸。","milRadio":"团队增益或救援技能后，其他队员回复 28 能量。","laptop":"控制技能后冷却 -2；常规行动后攻击 +4%、速度 +6%。","gtiAntenna":"烟幕技能后，其他队员回复 22 能量。","milShell":"爆破技能后，追加 125% 攻击的全体爆炸。","claudiusBust":"防护技能后，全体前排获得 22% 生命护盾。","spinoClaw":"持续伤害技能引爆最多 3 人，追加 140% 攻击；击杀后攻击 +8%、速度 +10%。","defibrillator":"治疗量 +40%，半血目标再 +50%。每轮首次治疗每名队友：净化、冷却 -1、回能 24。","robotVacuum":"低温技能追加 2 层低温；常规行动后防护 +8%。","binoculars":"侦察技能后，对一名已标记敌人追加 90% 攻击射击。","radio":"控制技能后，自身普通技能冷却 -1。","watch":"防护技能后，全体前排获得 16% 生命护盾。","heart":"战斗内主动：随时跳过当前交战及全部增援，领取胜利奖励。","ocean":"攻击 ×1.99；受到伤害降低 99%。主动「海浪冲击波」：全队护盾补满，对场上全体敌人造成 9,999,999% 攻击力伤害。","tally":"普攻后攻击 +8%、速度 +5%，可无限叠层。","pulseCore":"每轮首次大招后，攻击 +15%、速度 +20%，可无限叠层。","lighter":"爆破技能后，追加 45% 攻击的全体爆炸。","tea":"造成的治疗量 +15%。","vein":"造成的治疗量 +30%。","caviar":"治疗量 +60%；溢出治疗的 75% 转为护盾。","scalpel":"治疗量 +35%。每轮首次治疗每名队友：净化、冷却 -1、回能 15。","filter":"烟幕技能后，全体前排获得 9% 生命护盾。","experiment":"持续伤害技能后，引爆最多 3 名受持续伤害的敌人，追加 90% 攻击。","quantum":"侦察技能后，其他队员回复 26 能量。","rotor":"常规行动后速度 +5%，最多 6 层。","bladeServer":"常规行动后速度 +12%，可无限叠层。","workerBee":"常规行动后攻击 +14%，可无限叠层。","mechanical":"面板速度的 80% 额外转为攻击。","graphicsCard":"面板攻击的 30% 额外转为速度。","mandelUnit":"转化产生的攻击和速度，可继续参与双向转化。"};
  const ruleNotes = {"rocketFuel":"前排行动后，按面板速度相对开战速度的增幅百分比积攒动量。满 100 消耗 100，追加一次行动；每轮最多一次，后排不触发。","rotor":"每层按开战速度加算，最高 +30%。不提供额外伤害或额外行动。","mechanical":"保留原速度。按未转化的面板速度计算，包含装备、队伍加成和战斗叠层，不把排序速度或伤害倍率视为面板属性。","graphicsCard":"保留原攻击。按未转化的面板攻击计算，包含装备、队伍加成和战斗叠层，不把伤害倍率视为攻击属性。","mandelUnit":"需同时佩戴名贵机械表和显卡。转化后的速度继续转为攻击，转化后的攻击继续转为速度，按最终收敛值结算。不带本藏品时，转化结果不参与再次转化。同名效果不叠加。","heart":"必须由上阵干员佩戴，前后排均可。进入战斗后点击藏品主动按钮，普通、精锐、高难挑战和首领节点均视为通过，包括全部增援波次；胜利资金、掉落与挑战奖励进入快递箱，不消耗藏品。未选择的节点、战术与补给不能跳过；保留跳过前的真实伤害与击杀，不将跳过的敌人计为实战击杀。","ocean":"被动仅佩戴者生效。攻击先叠加其他面板加成，再乘 1.99；转化得到的攻击同样享受该独立乘区。伤害减免独立结算，普攻、技能和持续伤害均有效，正数伤害最低保留 1 点。基础暴击率 +100%、暴击额外伤害 +200%。主动开战获得 1 次，全队每完成 3 次常规行动再获得 1 次，可累积；连射、追击、大招、免费技能不额外充次。手动释放且不占行动，为全队存活干员补满护盾（最大生命 50%），冲击当前在场全体敌人；不跳过后续增援。主动由存活佩戴者施放，后排也可使用。同名主动次数不叠加。"};
  const Arsenal = typeof module !== 'undefined' && module.exports ? require('./haff-arsenal-tactics.js') : root.HaffArsenalTactics;
  Arsenal?.relics(relics);
  const Tempo = typeof module !== 'undefined' && module.exports ? require('./haff-tempo.js') : root.HaffTempo;
  Tempo?.installRelics(relics, shortEffects);
  const labels = { hp:'生命', attack:'攻击', armor:'防护', speed:'速度', energy:'初始能量', chargeEfficiency:'充能效率',critRate:'暴击率',critDamage:'暴击额外伤害' };
  for (const [key, item] of Object.entries(relics)) {
    if (item.rule?.trigger === 'action') {
      item.effect = item.effect.replaceAll('常规行动', '行动');
      shortEffects[key] = shortEffects[key].replaceAll('常规行动', '行动');
    }
    if (item.rule?.stacks && item.rule.unlimited !== false) {
      item.rule.unlimited = true;
      item.effect = item.effect.replace(/最多 \d+ 层/g, "层数无上限").replace(/（最多 \+100%）/g, "（无上限）");
    }
    item.grid ||= [1, 1]; item.image = `assets/haff-war/relics/${key}.png`;
    item.sourceImage = `https://playerhub.df.qq.com/playerhub/60004/object/${item.objectId}.png`;
    item.statsText = Object.entries(item.bonus || {}).filter(([,value]) => value).map(([stat,value]) => `${labels[stat] || stat} +${value}${['chargeEfficiency','critRate','critDamage'].includes(stat) ? '%' : ''}`).join(' · ');
    const notes = [ruleNotes[key] || item.effect.replace(/^(?:至臻藏品 · )?(?:生命|攻击|速度|防护|充能效率)[^。]*。/, '')];
    if (item.link) notes.push('技能联动每位佩戴者每轮一次，不由普攻、协同或追加伤害触发。');
    if (item.rule?.trigger === 'action') notes.push('普攻连射每发分别触发；技能、大招、免费翻滚整次各触发一次，包含后排自动技能与大招。驻守支援每周期触发；协同、追加伤害和持续伤害不计。大招与免费翻滚仍保留当前行动轴回合。');
    if (item.rule?.trigger === 'attack') notes.push('连射普攻每发独立叠层；协同和追加伤害不叠层。');
    if (item.rule) notes.push('叠层仅对佩戴者生效，按开战面板加算，战斗结束清空。');
    item.details = notes.join('\n');
    item.effect = shortEffects[key];
  }
  if (typeof module !== "undefined" && module.exports) module.exports = relics; else root.HaffRelics = relics;
})(typeof window === "undefined" ? globalThis : window);
